### ISSUE TITLE
Crash when Vacuum attempts to interact with Thermal Dynamics Servos

### ISSUE THREAD

**Issue by YurgenJurgensen** [DaedalusGame/EmbersRekindled#103]
Crash: https://pastebin.com/0T4Ud5H9

A Vacuum will cause a clientside crash when attempting to push into a Thermal Dynamics Servo.

Reproduction:
Install Thermal Dynamics and Embers Rekindled.  Place Vacuum.  Place Itemduct on back face of Vacuum.  Place Servo on Duct.  Give Redstone power to Vacuum and Servo (or set Servo to ignore Redstone).  Throw any item into vacuum.

**Comment by DaedalusGame** [comment]
does this work with regular hoppers instead of the vacuum?
oh wait, i know why this happens, vacuums are inputting on the clientside and TD doesn't handle that well

**Comment by YurgenJurgensen** [comment]
I couldn't repro with regular hoppers, just the vacuum.
