### ISSUE TITLE
Runaway Server Utilization (v1.11-hotfix)

### ISSUE THREAD

**Issue by khift363** [DaedalusGame/EmbersRekindled#106]
I recently put together a server with a large, custom modpack, and in running this server I've discovered that the longer the server goes without restarting the more of the server's CPU is being used by one of Ember's event subscriber threads. Specifically it is the following thread:

net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent

At the time of writing this, the server has been running for about 12 hours consecutively, and LagGoggles is reporting that that thread is taking 15233 microseconds per tick to manage, using 30.46% of the total CPU utilization available. If I restart, it'll drop to under 1000 us/t, which is a reasonable place to be.

Nobody on the server has touched anything from Embers yet. Whatever this is, it has to be background or world gen related. I can make no promises that it isn't a mod interaction - there certainly are plenty of mods here to interact with. I don't believe LagGoggles is reporting incorrectly, though - upon reboot the server runs silky smooth, but the longer we go the more server ticks get skipped, so something is definitely ramping up as time goes on. At the moment it's not so bad that it can't be worked around, but it is a thing I am worried about and if this can't be fixed I may have to remove Embers from the modpack.

LagGoggles scan screens
Before restarting:
https://i.imgur.com/yZD0zcs.png

After restarting:
https://i.imgur.com/s3rAmws.png

Environment is a server running the following:
Minecraft v1.12.2
Forge v14.23.5.2778
Embers Rekindled v1.11-hotfix
Baubles v1.5.2
Soot v1.5
Many other mods

(One interesting thing I noticed in writing this post is that Twitch never downloaded Mystical Mechanics for the pack, despite it being listed as a dependency for Embers. Not sure what's happening there, but everything boots at the moment. If that somehow turns out to be related to the issue, then it's an easy fix at least.)

**Comment by khift363** [comment]
18 hours later and Embers has climbed to using 86% of the 50ms allotted to each tick. Embers alone is pushing the server below 20tps despite nobody even using it. This has jumped to the top of my major problems list for the server.
https://i.imgur.com/41MNNCc.png

**Comment by DaedalusGame** [comment]
I think I'm aware of the problem but I'm too busy to fix it right now

**Comment by khift363** [comment]
Do you know when you might be able to push a fix out? I unfortunately happened to use Embers ores for all of my non-vanilla ore gen since Embers happened to have all the non-vanilla ores in the pack, so unfortunately turning Embers off until the fix hits means some serious work.

I did another profile with another method, this time using Spark, and here was the output:
https://sparkprofiler.github.io/#a4QQzvgayG

With this, it's showing that "net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1203_ModifierShiftingScales_onServerTick_ServerTickEvent.invoke()" ran for 55% of the 60 second profiling period. I can say for certain that nobody on the server has made any Shifting Scales, let alone added it to any equipment. Are the Golems calling this, perhaps?

**Comment by DaedalusGame** [comment]
I'll look into this when I wake up tomorrow

**Comment by adventurerok** [comment]
Perhaps the issue is that every value in the cooldownTicksServer HashMap is decremented by 1 each tick but nothing is ever removed?
