### ISSUE TITLE
Can't get Dawnstone Anvil CT blacklist function to work

### ISSUE THREAD

**Issue by Not-February** [DaedalusGame/EmbersRekindled#108]
Based on every scrap of information I've been able to find(and being able to successfully remove repairing of specific items in _previous versions_ with a script more or less the same functionally), this should be correct but isn't.

I tested in a standalone instance with nothing but Embers Rekindled, JEI, and crafttweaker installed for an attempt at removing all repairs from a diamond sword as an example:
```

import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;
import mods.jei.JEI;
import mods.embers.DawnstoneAnvil;

#modloaded embers

#priority 1

DawnstoneAnvil.remove(<minecraft:diamond_sword>,<*>);
```

Using `/ct syntax` says it's correct when I use, but when I try to restart Minecraft to actually test it, CT errors out a ton and the changes don't apply.

```
[SERVER_STARTED][SERVER][ERROR] embers.zs:10 > a method available but none matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.api.item.IngredientAny)
This is usually an error in your script, not in the mod
remove(ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IItemStack)
```

I wouldn't be asking about it here if I hadn't tried looking literally everywhere else I knew to look that might have information on this, so I'm tentatively assuming it might be a bug.

**Comment by DaedalusGame** [comment]
use 
```
DawnstoneAnvil.blacklistRepair(<minecraft:diamond_sword>);
DawnstoneAnvil.blacklistMateriaRepair(<minecraft:diamond_sword>);
DawnstoneAnvil.blacklistBreakdown(<minecraft:diamond_sword>);
```
which lets you pick what standard thing you can't do with them. should be more flexible than literally getting rid of the recipe in general.

**Comment by Not-February** [comment]
Okay, so the syntax changed since I last checked, gotcha
