### ISSUE TITLE
Document Craft Tweaker Integration

### ISSUE THREAD

**Issue by Dragnier** [DaedalusGame/EmbersRekindled#110]
Are there any plans to add craft tweaker integration? I would love to be able to change/add/remove various recipes for things like the mixer centrifuge, melter, alchemy array, etc.

**Comment by TechnoMysterio** [comment]
Crafttweaker support is already in, it's just not documented on the Embers page. Documentation can be found on the Soot github page, as that's where it originally came from: https://github.com/DaedalusGame/Soot/wiki/CraftTweaker-Support

As for why the documentation hasn't been moved somewhere more convenient, I'm guessing either laziness or forgetfulness.

**Comment by DaedalusGame** [comment]
[Totally a thing now btw](https://github.com/DaedalusGame/EmbersRekindled/wiki/CraftTweaker-Support)
