### ISSUE TITLE
Crash on Startup Embers Rekindled

### ISSUE THREAD

**Issue by MaverickBrandy-AT** [DaedalusGame/EmbersRekindled#116]
My Minecraft Crashes on Startup with:
Mystical-Mechanics-API-1.12.2
Baubles-1.12-1.5.2
Embers-Rekindled-Mod-1.12.2

Crash Log:
https://pastebin.com/gQSaG3qR

Forge Version:
1.12.2-14.23.5.2775

**Comment by DaedalusGame** [comment]
update mystical mechanics

**Comment by MaverickBrandy-AT** [comment]
Works Fine Response Time 10/10
Service 10/10
Would post again :D 
Thank you for your quick answer
