### ISSUE TITLE
Excessive recipe loading time

### ISSUE THREAD

**Issue by codewarrior0** [DaedalusGame/EmbersRekindled#124]
The loading screen for Project Ozone 3 (minus WaitingTime) showed the game loading recipes at a pace of 4 or 5 per second. Pausing the game in the debugger yielded this stacktrace implicating Embers:

![image](https://user-images.githubusercontent.com/307683/52647658-3cfb2500-2e89-11e9-89b0-171dfdb5672f.png)

The game spent about a minute loading the Embers anvil recipes before moving on and loading the other 100,000 recipes in the next five seconds.

A quick glance shows that [`IngredientSpecial::cacheMatchingStacks`](https://github.com/DaedalusGame/EmbersRekindled/blob/rekindled/src/main/java/teamroots/embers/util/IngredientSpecial.java#L39) is iterating over every single item in the item registry; this kind of ingredient is used by AnvilRepairRecipe. To make it worse, [`AnvilRepairRecipe::getWrappers`](https://github.com/DaedalusGame/EmbersRekindled/blob/rekindled/src/main/java/teamroots/embers/recipe/AnvilRepairRecipe.java#L26) also iterates over every single item in the item registry, which means `cacheMatchingStacks` is called once for each (repairable?) item. 

Possibly related to #52

**Comment by DaedalusGame** [comment]
This is pretty much as optimized as it can be already. Repairables to repair items is a 1->n mapping, and finding all repair items for a repairable item is an O(n²) operation. However, it seems that IngredientSpecial has a rampant stream that really shouldn't be there. I don't think it will fix much of anything though.
