### ISSUE TITLE
scale hearts invisible

### ISSUE THREAD

**Issue by Alonlystalker** [DaedalusGame/EmbersRekindled#129]
![1](https://user-images.githubusercontent.com/1726962/53665024-4d7a1080-3c7b-11e9-86be-e7c9f6f22958.jpg)
Scales shards visible when broken but scaled hearts has no any covered texture.

**Comment by Bluberry-Kat** [comment]
what's your modlist?

**Comment by DaedalusGame** [comment]
i think this is some kind of mantle issue and i think it's fixed in dev

**Comment by Alonlystalker** [comment]
my mods

> AmbientSounds_v2.3_mc1.12.2.jar
animania-1.12.2-1.6.2.jar
AppleSkin-mc1.12-1.0.9(1).jar
appliedenergistics2-rv6-stable-6.jar
Aquaculture-1.12.2-1.6.8.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-26.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8(1).jar
BiblioCraft[v2.4.5][MC1.12.2].jar
Bookshelf-1.12.2-2.3.576.jar
Botania+r1.10-360.jar
BrandonsCore-1.12.2-2.4.9.195-universal.jar
Cavern_1.12.2-v2.1.9.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-0.2.1.35.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.2.25-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CTM-MC1.12.2-0.3.3.22.jar
Draconic-Evolution-1.12.2-2.3.20.333-universal.jar
DynamicSurroundings-1.12.2-3.5.4.3.jar
EmberRootZoo-1.12.2-1.3.10.jar
EmbersRekindled-1.12.jar
EnchantingPlus-1.12.2-5.0.176.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
ExtraCells-1.12.2-2.6.2a.jar
FancyBlockParticles-1.12.x-2.4.1.jar
Farseek-1.12-2.3.1.jar
Ferdinand's+Flowers-1.12.x-1.10.4.1.jar
foamfix-0.10.3-1.12.2.jar
GardenStuff-1.12-2.1.1(1).jar
Geolosys-1.12.2-2.1.3.1.jar
GraveStone-1.12.2-Graves-1.1.0.jar
GrimoireOfGaia3-1.12.2-1.6.4.jar
HammerCore-1.12.2-2.0.4.2.jar
HardcoreDarkness-MC1.12.2-2.0.jar
ImmersiveCables-1.12.2-1.3.2.jar
ImmersiveEngineering-0.12-89.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10(1).jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.13.1.220.jar
journeymap-1.12.2-5.5.2.jar
JurassiCraft-1.12.2-2.1.17.jar
llibrary-1.7.15-1.12.2.jar
Mantle-1.12-1.3.3.42.jar
moartinkers-0.6.0(1).jar
mowziesmobs-1.4.2.jar
natura-1.12.2-4.3.2.62.jar
NaturesCompass-1.12.2-1.5.1.jar
notenoughroofs-1.12.2-0.8.0.0.jar
OceanFloor-1.12-1.0.1.jar
OptiFine_1.12.2_HD_U_E2.jar
OreLib-1.12.2-3.5.2.2.jar
Pam's+HarvestCraft+1.12.2zb.jar
Psi-r1.1-72.jar
Quark-r1.5-146.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
RebornCore-1.12.2-3.13.5.421-universal.jar
RecurrentComplex-1.4.7.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
SereneSeasons-1.12.2-1.2.15-universal.jar
SophisticatedWolves-1.12.2-3.13.7.jar
SoulShards-TOW-1.12-2.7.6-56.jar
Streams-1.12-0.4.4(1).jar
TConstruct-1.12.2-2.12.0.115.jar
TechReborn-1.12.2-2.20.13.940-universal.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAdditions-1.12.2-12r.jar
ThermalExpansion-1.12.2-5.5.3.41-universal.jar
ThermalFoundation-1.12.2-2.6.2.26-universal.jar
tinkersdefense-1.4.2.23.jar
TinkerToolLeveling-1.12.2-1.0.5.jar
twilightforest-1.12.2-3.8.689-universal.jar
wolfarmor-1.12.2-2.2.3.1798-universal.jar

**Comment by Alonlystalker** [comment]
> 
> 
> i think this is some kind of mantle issue and i think it's fixed in dev

have latest versions of embers and mantle

**Comment by DaedalusGame** [comment]
dev means not released
