### ISSUE TITLE
Cant Remove clockwork Recipe with CT

### ISSUE THREAD

**Issue by admiralgachi** [DaedalusGame/EmbersRekindled#131]
recipes.remove(<embers:staff_ember>.withTag({cooldown: 0}));

recipes.removeShaped(<embers:staff_ember>.withTag({cooldown: 0}));

recipes.remove(<embers:axe_clockwork>);

recipes.removeShaped(<embers:axe_clockwork>);

recipes.remove(<embers:pickaxe_clockwork>);

recipes.removeShaped(<embers:pickaxe_clockwork>);

recipes.remove(<embers:grandhammer>);

This are the line of code that i use with CraftTweaker,worked with every other object but not with the clockwork item,i tried everyone with the remove and removeShaped , with the Tag and without the Tag.
What am i doing wrong?

**Comment by DaedalusGame** [comment]
try removing by the recipe name `"embers:axe_clockwork"` instead. I'm not sure whats going wrong there, since it's not a special recipe, but removing by recipe name should work always.

**Comment by admiralgachi** [comment]
Yea it worked thx man.
