### ISSUE TITLE
Found a broken recipe

### ISSUE THREAD

**Issue by renadi** [DaedalusGame/EmbersRekindled#143]
When starting my modpack I get this message spamming my log literally 100+ times.

Found a broken recipe: teamroots.embers.recipe.AnvilRepairFakeRecipe@5085c425 Failed to get ingredients from recipe wrapper java.lang.IllegalArgumentException: Stack can not be invalid! at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:499) at vazkii.psi.common.item.tool.IPsimetalTool.isRepairableBy(IPsimetalTool.java:104) at . . .

https://pastebin.com/q1euKQXw

Also JEI is apparently trying to register 811,121 recipes which seems like a lot.  I'm not sure if it's related, but the two together seem like they could.

**Comment by SirAron111** [comment]
https://pastebin.com/6gxESbmA jep haveing the same issue made a post here to https://github.com/mezz/JustEnoughItems/issues/1534

**Comment by LlubNek** [comment]
Same thing here. JEI does not like AnvilFakeRecipe at all.
Lot more than a hundred though... JEI seems to think there are 204850 recipes in my modpack and the vast majority seem to be these.

[latest.log](https://github.com/DaedalusGame/EmbersRekindled/files/3028461/latest.log)

**Comment by Cazadorsniper** [comment]
The same issue that Psi and Embers have also happens with Thermal Solars.

**Comment by Sunconure11** [comment]
@mezz

**Comment by Compegen** [comment]
What's the status of this issue? I am still getting it in the latest release (1.13)

**Comment by DaedalusGame** [comment]
considering this was opened after the latest release this shouldn't come as a surprise

**Comment by Tanto17** [comment]
Just an FYI, I am still getting this with Embers version 1.13 with the two latest hotfixes. The Fake Anvil recipe kills my load times. I had to kill minecreaft myself. 
[2020-04-07-3.log](https://github.com/DaedalusGame/EmbersRekindled/files/4446362/2020-04-07-3.log)

**Comment by Almaravarion** [comment]
For the record - issue appears with 1.14 version of Embers: Rekindled hotfix version from Curseforge [dated at 7/21/20],

**Comment by DaedalusGame** [comment]
log?
