### ISSUE TITLE
Golems not affected by mob force field from astral sorcery

### ISSUE THREAD

**Issue by ajisrael** [DaedalusGame/EmbersRekindled#144]
When playing in astral sorcery there is a ritual called Armara. This creates a force field like effect in which all mobs are pushed out of the area to keep your base safe. All mobs except the golems from embers are affected. I have tried looking into the config files of both mods and do apologize if I have missed something. If there was a way to configure this to have it so the golems are affected that would be greatly appreciated.

**Comment by DaedalusGame** [comment]
this might be because golems are 100% knockback resistant

**Comment by ajisrael** [comment]
Yeah someone from astral sorcery just explained that is the reason. Is there a way to change the knockback fo the golems so they can be affected?
