### ISSUE TITLE
Codex Entry for Geologic Separator

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/EmbersRekindled#153]
To make sure people know that the Geologic Separator is a thing, perhaps add a codex entry for it, connected to the Melter entry so it appears once the Melter page is checked off. Give a rundown of where to attach it to (bottom/top), what bonuses you get (or just tell them to look at JEI), and what happens when you use multiple Separators (mentioning max amounts if that's a thing).

As a side note, it might be good to update the ore entry to mention the ores that were previously optional, and thus were not included. Could even split it into multiple pages now that that's possible.

**Comment by 3LilyFarmer** [comment]
I don't even know how to make it work, so some info/tutorial might be helpful.
