### ISSUE TITLE
Ancient Codex losing progress (checked entries) after client closes

### ISSUE THREAD

**Issue by sandalle** [DaedalusGame/EmbersRekindled#162]
Whenever I close my Minecraft client all the way (not just disconnect; disconnect and reconnect seems to keep progress), all of my checked progress in the Ancient Codex is "lost" and I need to re-check (right-click) on what I've already done to unlock the entries.

I don't know when this starting showing up, I just started using Embers (thank you for continuing it! :) ) on this modpack.

Minecraft 1.12.2 (both SSP and SMP)
Forge Mod Loader: 1.12.2-14.23.5.2836

Mod List: https://github.com/sandalle/nst-world-of-color
EmbersRekindled-1.13-hotfix2

Embers config: https://github.com/sandalle/nst-world-of-color/blob/master/config/embers.cfg

~I've tried setting both of these to false to test, but it didn't help:~
Setting these values to `false` (when spelled correctly ;) ) works around the issue:
```
    # Codex category is shut. Progression is open. [default: true]
    B:codexCategoryIsProgress=false

    # Codex entry is shut and hide. Progression is open and show. [default: true]
    B:codexEntryIsProgress=false
```

This happens whether I use the Ancient Codex combined with the [Akashic Tome](https://minecraft.curseforge.com/projects/akashic-tome) or with the Ancient Codex itself (not in the Tome).

**Comment by DaedalusGame** [comment]
`flase` instead of `false` on the second config may be causing one of your problems

**Comment by sandalle** [comment]
Thanks @DaedalusGame , spelling `false` correctly does _indeed_ help. ;) I also tested SSP and the same issue occurs there.
