### ISSUE TITLE
Natura's fusewood tools can be used to make iron on dawnstone anvil???

### ISSUE THREAD

**Issue by Water-Moon** [DaedalusGame/EmbersRekindled#173]
![图片](https://user-images.githubusercontent.com/43123946/58908721-e79e9880-8743-11e9-9f47-50c3bcfacfe3.png)
![图片](https://user-images.githubusercontent.com/43123946/58908800-1ddc1800-8744-11e9-906f-85f09bb9b7ec.png)
![图片](https://user-images.githubusercontent.com/43123946/58908813-26345300-8744-11e9-88dd-4d9437ac40a0.png)

This is what happened.
As players can plant fusewood tree, they can thus effectively massively produce a magnificent amount of iron.
Have no idea why this is the case.

**Comment by DaedalusGame** [comment]
natura problem. they apply the iron toolmaterial to their tools.
