### ISSUE TITLE
Game Crash when I mine the Item Transfer

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/EmbersRekindled#174]
Hello,
In my game, I try to mine the Item Transfer Block, with a filter set  for Ember Shard and the game instantly crash just after I saw the block droping in the ground. I look the Crash log and look like the issue is caused by the Item Transfer...

crash report:
https://gist.github.com/Fireztonez/edcb409a64ca8a244e57bfd7d1e38e30

version:
Forge: 14.23.5.2838
Embers Rekindled 1.13-Hotfix 2
Soot: 1.6

If you need more informations, let me know
Fireztonez

**Comment by DaedalusGame** [comment]
Try without Nuclearcraft

**Comment by DaedalusGame** [comment]
did anything ever come of this

**Comment by Fireztonez** [comment]
:o sorry I just saw the reply, my bad... I will try again if I can reproduce the crash and after I will try if the issue is still there without Nuclearcraft. I let you know soon!

**Comment by Fireztonez** [comment]
I can't reproduce right now, so, the problem is probably fixed with somes mods updates I have done...

If I have a new issue I will open a new report.
Thank's
Fireztonez
