### ISSUE TITLE
Melter recipes aren't being removed by crafttweaker

### ISSUE THREAD

**Issue by Trevor-Mansfield** [DaedalusGame/EmbersRekindled#175]
Embers Rekindled: EmbersRekindled-1.13-hotfix2.jar
Soot: Soot-1.6.jar

I'm trying to use crafttweaker to redo the melter recipes. I have tried these 3 ways to remove the ore -> molten metal recipe: 

```
for liquid in liquidsTier8All {
	meltr.remove(liquid);
	meltr.remove(liquid*288);
}

for item in oresTier8All {
	meltr.remove(item);
}
```

The recipe is still there though. I originally only had Embers but the recipe wasn't removing, so I added Soot to see if they would remove then, but they still don't. The global variables are defined [here](https://github.com/Trevor-Mansfield/Chain-Automata/blob/master/scripts/globals.zs) and the script I'm trying to call it from (much less organized sorry) is [here](https://github.com/Trevor-Mansfield/Chain-Automata/blob/master/scripts/embers.zs). The recipe I'm adding is registering though and displays in JEI, it's just because of the conflict the default is used instead of mine when I actually put ore in the melter. There are no errors when I run `/ct syntax`.

**Comment by DaedalusGame** [comment]
```
mods.embers.Melter.remove(<minecraft:iron_ore>);
mods.embers.Melter.remove(<liquid:copper>*288);
```
both of these lines correctly remove copper and iron ore melting respectively, so this is probably an error in your script

**Comment by DaedalusGame** [comment]
your globals script is missing a lot of the embers fluids, you put a lot of `liquid:molten_<x>`, embers uses only `liquid:x`

no idea why removal by itemstack isn't working for you though

**Comment by Trevor-Mansfield** [comment]
Yup, you're right about the liquids - they are the metallurgy versions, my bad. Those are what I wanted to produce I just thought maybe it'd work since the IItemStack wasn't. I'll try using the correct liquid when I have time later, but I'm still not sure why the ore doesnt work. I don't know if it's related, but when I run JEIs.removeAndHide on lead ore and ingots in a different script it also leaves those recipes in but there is no icon for the input and it still shows molten lead being created.

**Comment by Trevor-Mansfield** [comment]
Yes! Thank you, removal using the ILiquidStack from Embers works correctly. I'm still lost how the ore didn't work though.

**Comment by Trevor-Mansfield** [comment]
I hadn't renamed something correctly in my script, it was all 2's instead of 1-2-3... Sorry for being a dud and wasting your time.
