### ISSUE TITLE
Confused about mini-boilers

### ISSUE THREAD

**Issue by bloche1871** [DaedalusGame/EmbersRekindled#180]
Not entirely sure if this is a bug or not, but if I have 4000mb of water inside a mini boiler attached to a pressure refinery, it all turns into steam instantly and explodes before it can be piped out because the resulting amount of steam is over the 16000 capacity limit of the boiler. If I have 3000mb of water, it turning to steam instantly causes no problem because the result is 15000mb of steam, and the steam can be piped out.
Am I doing something wrong? Am I supposed to be micromanaging water input into the boiler to keep it from being too full even if nothing is preventing the steam from escaping? It seems to me that having steam be gradually produced from water instead of all at once would make more sense, allowing it to be piped out as it is produced (or having a smaller tank size for water than for steam would also make sense).

**Comment by DaedalusGame** [comment]
yes, this is intentional, the steam conversion is proportional to how much ember a machine consumes/produces.
you can use a pressure refinery for big steam output, but at your own risk
using an ember activator or a melter/cinder plinth is a much safer way to produce steam
i may add bigger boilers from more expensive materials later on

**Comment by bloche1871** [comment]
Ah thanks for the clarification! I was thinking of using Crafttweaker to change the water to steam ratio to match Extreme Reactors' 1:1 ratio (Ideally I would probably change Extreme Reactors' to match Embers, but it doesn't seem to be possible), I guess it would make using the pressure refinery for steam much less dangerous then... I wonder if that would cause any other issues or balance changes (would it result in just more water being consumed, or would there be less steam produced per heat?).

**Comment by DaedalusGame** [comment]
the amount of fluid boiled is equal to the amount of heat produced. there's a modifier for this in the config. each mb of fluid is then turned into some quantity of gas based on the modifier you set with CT.
