### ISSUE TITLE
Bug: Ancient Codex not properly saving progress

### ISSUE THREAD

**Issue by SirAron111** [DaedalusGame/EmbersRekindled#182]
Bug: Ancient Codex not properly saving progress (the sections marked as read by right clicking them that gives the little green tick) so when marking them I can exit the works and reenter just fine but when I close the client completely and run it back up again the codex is reset to 0 progression -. - Kind of annoying having to retick all the marks again to continue reading it after a break.

I like the new unlocking feature but it doesn’t save player progress properly not on single player and not on servers.

**Comment by KittyKitCatCat** [comment]
Never been an issue for me all I can tell you.

**Comment by DaedalusGame** [comment]
~~i confirmed this issue a month ago~~

*several months ago

dupe of #162
