### ISSUE TITLE
Request/Bug - Block Breaker can break bedrock and other unbreakable blocks

### ISSUE THREAD

**Issue by Fireztonez** [DaedalusGame/EmbersRekindled#183]
Hello,
I just test in my modpack, to place a bedrock block in face of the Block Breaker and the block breaker break the bedrock block like any other block. Ok the block is not drop, but, I think bedrock should be blacklisted by default.

And at the same time, I think having a config option for blacklist somes blocks with the blocks breaker should be nice!

Version:
Embers Rekindled: 1.13-hotfix2
Forge: 1.12.2 - 14.23.5.2838

Thank's

**Comment by KittyKitCatCat** [comment]
I don’t think embers rekindled has a block breaker. I don’t see how it’s related to embers, when I was playing a modpack with embers and a bunch of block breakers from other mods everything was fine. Did embers receive an update I’ve missed maybe?

**Comment by DaedalusGame** [comment]
it's had a block breaker for forever lol
