### ISSUE TITLE
Recipe removal priority issue.

### ISSUE THREAD

**Issue by MightyBidoof** [DaedalusGame/EmbersRekindled#186]
Title is pretty self-explanatory, but to elaborate:

File structure looks like so;
File containing removeAll function:
``Embers/RemoveAll.zs``
File containing Melter recipes:
``Embers/Mixer/MelterOre.zs & MelterIngot.zs``
So file ordering isn't a potential issue.
This can be remedied by putting ``#priority 1`` to tell Crafttweaker to run the removal first, but ideally this shouldn't be something someone has to do.

An easy enough fix for this is either having the method call upon the priority function by default, or adding a tag to each recipe added by Crafttweaker.

Screenshot of the Crafttweaker log, showing the recipes being added and subsequently removed.
![Ditto to text above](https://user-images.githubusercontent.com/12218253/62884203-d8ccf700-bd2d-11e9-9a41-228cca287ca1.png)

Screenshot of the Crafttweaker log after adding the line ``#priority 1`` to the top of the script, and ideally how it should look no matter what.
![Ditto to text above](https://user-images.githubusercontent.com/12218253/62884331-2ba6ae80-bd2e-11e9-9e73-c046e5b116ab.png)

Note: This also happens (or at-least used to happen) if you remove a recipe via output, and then add another recipe with the same output

Apologies if an issue has already been opened about this, but I wasn't able to find one.

**Comment by DaedalusGame** [comment]
Wont fix for simplicity's sake. There's already mechanisms (as you've mentioned) in CT to circumvent this.
