### ISSUE TITLE
What's the name of the fakeplayer?

### ISSUE THREAD

**Issue by huangsijun17** [DaedalusGame/EmbersRekindled#198]
I want to give op, if not Breaker doesn't work in the territory of the FTB setting.

**Comment by DaedalusGame** [comment]
`new GameProfile(new UUID(13, 13), "embers_breaker")`

**Comment by huangsijun17** [comment]
> `new GameProfile(new UUID(13, 13), "embers_breaker")`

I had add op :`embers_breaker`, `[embers_breaker]`, 'embers', '[embers]', but no working.

**Comment by huangsijun17** [comment]
Name is [minecraft]. I fonded it.
