### ISSUE TITLE
Ancient Golem not spawning

### ISSUE THREAD

**Issue by Excederus** [DaedalusGame/EmbersRekindled#232]
For some reason the Golems are not spawning in my modpack.

Here is a latest log and the modlist taken from exporting the modpack from Twitch App.
Mods that are not in the modlist: Underground Biomes Construct, Optifine, Nutrition
[latest.log](https://github.com/DaedalusGame/EmbersRekindled/files/4302563/latest.log)

[modlist.txt](https://github.com/DaedalusGame/EmbersRekindled/files/4302564/modlist.txt)

**Comment by DaedalusGame** [comment]
your modlist is huge, chances are there's too many things taking up spawn slots

**Comment by BlackQuests** [comment]
I'm having the exact same issue. I first suspected that other mods might be taking up spawn slots but I'm not so sure. Did you manage to fix your issue? We've got a slightly similar modslist.
[modlist.txt](https://github.com/DaedalusGame/EmbersRekindled/files/4493691/modlist.txt)

**Comment by DaedalusGame** [comment]
Here's some cliffnotes:
- Golems spawn in ocean biomes
- Golems spawn in COLD, DESERT, ICY and WARM biomes
- smallRuinChance is inverse of what it says it is, so higher config value means lower chance to spawn
- Small ruins spawn in any block extending BlockStone
