### ISSUE TITLE
Seem to have an issue with ember particles on my server.

### ISSUE THREAD

**Issue by Caffeinew** [DaedalusGame/EmbersRekindled#233]
I run a custom modpack server, and the "ember transition" from place to place seems fine, if you test it in single player. But if player builds anything on the server, the animation bugs out, leading to particles just going in the straight line. 
![image](https://user-images.githubusercontent.com/61048648/77617681-ce224380-6f45-11ea-8daa-63a8e1742f36.png)

**Comment by DaedalusGame** [comment]
you're either using sponge or valkyrian warfare

**Comment by Caffeinew** [comment]
> you're either using sponge or valkyrian warfare

i'm using sponge, any fixes ?

**Comment by DaedalusGame** [comment]
no clue, if the normal forge stuff works different on a sponge server there is pretty much nothing i can do.
