### ISSUE TITLE
AnvilRecipe error taking forever to load

### ISSUE THREAD

**Issue by Tanto17** [DaedalusGame/EmbersRekindled#236]
I think there is a lot going wrong in my minecraft (it suddenly stopped working after I updated something (separate issue))...

One of the things that started happening is that my logs started getting spammed by hundreds of embers fake anvil recipe errors with JEI. This is causing me to take forever to load... Over 10 minutes and I end up having to kill minecraft myself. It makes it hard to problem solve my other issues. Any ideas why this started happening? It was working fine a few weeks ago. 

[latest.log](https://github.com/DaedalusGame/EmbersRekindled/files/4463378/latest.log)

Any help would be appreciated, 
Thanks for your time!

**Comment by DaedalusGame** [comment]
This looks like a betweenlands issue. They put an itemhandler capability on every item and then proceed to error out on every single serialize.

**Comment by Tanto17** [comment]
Wow that was a quick reply ! thanks Ill try removing the betweenlands!

**Comment by Tanto17** [comment]
Yup Removing the Betweenlands Fixed my loading issue. Still crashed on loading a world but it has nothing to do with embers:
https://paste.dimdev.org/yokisodosu.mccrash

Thanks for your help!

**Comment by DaedalusGame** [comment]
thats the same issue. try updating forge, it's very unlikely that two different mods cause the exact same problem like that.

**Comment by Tanto17** [comment]
I am on the latest version of forge for 1.12.2. 
 forge-1.12.2-14.23.5.2852.

**Comment by DaedalusGame** [comment]
try downgrading to the latest 1.12.2 version, 14.23.5.2847

**Comment by Tanto17** [comment]
Thanks for your help, trying now.

**Comment by Tanto17** [comment]
Nope same thing: 
https://paste.dimdev.org/quqihivinu.mccrash

**Comment by Tanto17** [comment]
I still have no idea what is going on and yah it is the same error. I made a post about it on reddit but well no idea so far. https://www.reddit.com/r/ModdedMC/comments/fxd8iy/need_help_with_recent_crash_1122_mixin_related/
