### ISSUE TITLE
Mixing Centrifuge recipe removal doesn't work correctly

### ISSUE THREAD

**Issue by ZombieKonsti** [DaedalusGame/EmbersRekindled#239]
Trying to remove Mixing Centrifuge Recipes with crafttweaker doesn't seem to do anything other than printing that the recipe was removed to the console.

Embers: 1.13-hotfix2
Forge: 14.23.5.2854
Crafttweaker: 4.1.0.20.564

Adding recipes however works perfectly.

Methods used:
  mods.embers.Mixer.remove(<liquid:dawnstone>);
    (This doesn't work, still shows up in jei and still craftable)

  mods.embers.Mixer.add(<liquid:dawnstone>*8,[<liquid:bronze>*4,<liquid:electrum>*4]);
    (This method works as intended, recipe visible in jei and craftable)

CT Log:
[crafttweaker.log](https://github.com/DaedalusGame/EmbersRekindled/files/4601464/crafttweaker.log)

**Comment by DaedalusGame** [comment]
`mods.embers.Mixer.remove(<liquid:dawnstone>*8);`

**Comment by ZombieKonsti** [comment]
Ok thanks, didn't know you needed to specify the amount  when removing. Also i just noticed, i forgot the brackets in the examples, as i didn't copy paste them here. Sorry if i bothered you.
