### ISSUE TITLE
Crash when looking at Artisan Automation's block while wearing Ashen Goggles

### ISSUE THREAD

**Issue by SeriousCreeper** [DaedalusGame/EmbersRekindled#240]
Crash Report: https://pastebin.com/QbvE34iS 

When i look at the "Mechanical Artisan" block (the glass looking one, which has to be placed on top of the Artisanal Power Converter) with the ashen goggles on, it causes that crash. 

Using EmbersRekindled-1.13-hotfix2 and Artisan Automation.

Cheers,
SeriousCreeper

**Comment by DaedalusGame** [comment]
Seems to be fixed on their end
