### ISSUE TITLE
Config Option to Remove Inscription Stamp Recipes from JEI

### ISSUE THREAD

**Issue by Kenja-mc** [DaedalusGame/EmbersRekindled#242]
I'm a packdev making a 1.12.2 modpack with Embers for my friends who are pretty new to modded Minecraft. 

I think it could get really confusing for my players if they see the only way to craft something without a crafting recipe is to use an inscription stamp. It can get even more confusing considering that the items change as if they're an oredicted recipe like shown here:

![image](https://user-images.githubusercontent.com/18564584/83714288-f25a6a80-a5ef-11ea-8b7d-369649b1de0e.png)

I'm going to try removing the inscription stamp recipes with Crafttweaker, but I would appreciate it if this small change was implemented.

Thanks in advance.

**Comment by majijn** [comment]
https://github.com/DaedalusGame/Soot/issues/90
