### ISSUE TITLE
Geologic Separator crafttweaker support

### ISSUE THREAD

**Issue by Pseudonomenclature** [DaedalusGame/EmbersRekindled#243]
Some of the Geologic Separator bonus outputs are a bit inconsistent with the bonus outputs of other mods, and it'd be great if we'd be able to change what the bonus output is + its amount using crafttweaker. Personally I need it for my on modpack for consistency and balance improvement.

Someone was going to ask for this eventually.

**Comment by DaedalusGame** [comment]
Melter.add(ILiquidStack output, IIngredient input, ILiquidStack bonus)

**Comment by Pseudonomenclature** [comment]
Works like a charm.
