### ISSUE TITLE
Missing Textures on a different mod after the 1.14 update

### ISSUE THREAD

**Issue by Sereath** [DaedalusGame/EmbersRekindled#251]
Just a heads up

After updating to **1.14-hotfix** from **1.13-hotfix2** we started getting missing textures on some of the items from Techguns, version 1.12.2-2.0.2.0_pre3.2. However this only seems to happen within the JEI UI.

**1.13-hotfix2**
![image](https://user-images.githubusercontent.com/54506307/89021969-eedd1a00-d2e6-11ea-9200-d80bdcdeb7b5.png)

**1.14-hotfix**
![image](https://user-images.githubusercontent.com/54506307/89022001-f7cdeb80-d2e6-11ea-8da0-f8e66c43839d.png)

 In the meantime we will be going back to 1.13-hotfix2

**Comment by DaedalusGame** [comment]
https://github.com/pWn3d1337/Techguns2/issues/149
