### ISSUE TITLE
Crash on launch?

### ISSUE THREAD

**Issue by Yourname942** [DaedalusGame/EmbersRekindled#252]
Does anyone know how to fix this error/ crash?

latest log: https://gist.github.com/Yourname942/2edaf002750d43d00cbea5e44bea47ae

crash log: https://gist.github.com/Yourname942/ca20cb4361224fb5f779fd517897bcae

Thank you.

**Comment by DaedalusGame** [comment]
Wrong repo https://github.com/Peatral/EmbersConstruct/issues
