### ISSUE TITLE
Dawnstone Anvil Weirdly Picky About Repair Material For Items

### ISSUE THREAD

**Issue by TeetoKaziim** [DaedalusGame/EmbersRekindled#253]
I seem only able to repair items with the ore dictionary item corresponding to their repair material, if that item comes from the same mod as the item being repaired.

Example: I have _Dungeon tactics_ , _Tinker's Complement_, and _Ancient Warfare_.
All 3 add steel ingots. Tinkers and Dungeon add steel armor.

But I only seem able to repair Dungeon Tactics' Steel armor with the dungeon tactics steel ingots. The Ancient Warfare and Tinkers' complement ones do not work; giving the hammer a redstone signal results in no-action.

_Very Good Screenshot Capturing the Inaction In Action_
![image](https://user-images.githubusercontent.com/25490944/90378142-99bb3b00-e03e-11ea-81e9-4e6f9f1756d5.png)
_I am not certain how best to capture this, pictured is the hammer not mashing an Ancient Warfare ingot into my Dungeon Tactics Armor_

The JEI recipes for the dawnstone anvil repair recipes actually reflect this limitation: It does not cycle through the matching ore tag items, it shows only the specific one. This behaviour appears to be matched attempting to use Amethyst Gems from _NetherEx_ to repair _Mystical World_ tools, _Embers_ Silver Ingots to repair _Dungeon Tactics_ Silver equipment, and other similar situations.

**Comment by TeetoKaziim** [comment]
Also tested in an environment with just JEI, Dungeon Tactics and Embers Rekindled installed, just to be sure. Still occurs. (One mod's Silver Ingot will still not repair the other mod's silver armor/tools)

**Comment by DaedalusGame** [comment]
Have you tried this in an anvil before?

**Comment by TeetoKaziim** [comment]
So I'm ... apparently kinda silly. I guess I boldly assumed a lot of things. And some of those things are wrong.

![image](https://user-images.githubusercontent.com/25490944/90397646-c6327f80-e05d-11ea-9ab7-cd3c104ab28c.png)

It doesn't seem to work in an anvil either. So ... the problem is not your fault.

I'mma close this.
