### ISSUE TITLE
Inferno Forge doesn't function.

### ISSUE THREAD

**Issue by LegoKirbyMan** [DaedalusGame/EmbersRekindled#255]
For some reason my Inferno Forge doesn't upgrade my tools, even though I do everything right.
I toss in a fully "heated" tool, some ember crystals and connect to a fully charged core. The ember gauge on the mechanical core displays full charge of 32000. When I close the hatch, the smoke effect starts as intended, but after a couple of seconds abruptly stops, as if power was cut, however it is not: the gauge shows that the forge consumed about 2000 ember, but the core is still full. The fireball effect does not happen and the crystals don't get consumed, and, as expected, the tool doesn't level up. Is there a fix to that? It happens every time I try to do that.

**Comment by DaedalusGame** [comment]
use less crystals, the current max is 3 clusters worth

**Comment by LegoKirbyMan** [comment]
I tossed in just 7 normal crystals, as was shown in the tutorial.

**Comment by LegoKirbyMan** [comment]
When that didn't work I tossed 10, then entire stack, but still no effect.

**Comment by LegoKirbyMan** [comment]
I suggest telling the player in the codex that there is some limit, because as I checked it may not be only my problem.

**Comment by DaedalusGame** [comment]
3 clusters = 9 shards + 3 crystals = 27 shards or any combination thereof
the limit will be extended and configurable come next version, this is an ancient bug resurfaced by a fix that made multiple crystals work et all.
i'm not too worried about it because you're getting a monster bargain :P

**Comment by LegoKirbyMan** [comment]
Thanks! I just added exactly 3 clusters and it (finally) worked! But I still would advise providing better ingame information than "T
he more Ember crystal you put in, the more likely you succeed." because players may assume that there is no limit.
