### ISSUE TITLE
Mithril isnt real

### ISSUE THREAD

**Issue by earthman2** [DaedalusGame/EmbersRekindled#256]
I just got this mod and when i loaded into a previous mod testing world this happened 
![image](https://user-images.githubusercontent.com/69991658/90827778-b206b080-e2f1-11ea-8b0a-3f512ebdc77e.png)

**Comment by earthman2** [comment]
Should i just hit yes or do i need to do something else

**Comment by DaedalusGame** [comment]
hit yes, mithril has been unobtainable in the old version of embers and iron nuggets are rightly removed aswell

**Comment by earthman2** [comment]
so do i just hit yes?

**Comment by earthman2** [comment]
wait nvm

**Comment by earthman2** [comment]
> 
> 
> hit yes, mithril has been unobtainable in the old version of embers and iron nuggets are rightly removed aswell

thank you
