### ISSUE TITLE
Latest update (1.15) causes visual bug with Hooked mod

### ISSUE THREAD

**Issue by ghost** [DaedalusGame/EmbersRekindled#276]
This doesn't seem to be an issue in previous versions, but after updating I was having an issue with textures that would otherwise be transparent rendering as black. I don't if this is an issue any other places, but I've observed it with the chain texture from Hooked.

![2020-12-31_15 03 21](https://user-images.githubusercontent.com/22355405/103425569-03b52680-4b81-11eb-9599-00042cf4e685.png)

**Comment by DaedalusGame** [comment]
great chance this was caused by #261 turning alpha off after rendering particles...

**Comment by ghost** [comment]
Would it make sense to put in a config option to disable the turning off alpha since if I'm right #261 was only sometimes a problem in previous versions?

**Comment by abundzu** [comment]
I think this may also be causing textures for the guns from techguns in JEI to go missing. Does not seem to cause an issue with version 1.13 hotfix2 but does with 1.14+. On the hotbar they are fine but in JEI show up as purple and block boxes

**Comment by DaedalusGame** [comment]
no, that techgun issue is different, the techgun dev supposes that it's some coremod in mystmech interfering with his coremod but mystmech doesn't use any coremods, and he refuses to investigate further.
