### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by SSKirillSS** [DaedalusGame/EmbersRekindled#28]
Hello, I`m starting the game whith the new Embers(Rekindled) and Soot on my test modpack for check updates, but game are crash on initialising stage - https://pastebin.com/gmThs44S (with another mods) and https://pastebin.com/nbAmcvGS (with no mods);

**Comment by DaedalusGame** [comment]
oops, accidental bauble harddep

**Comment by SSKirillSS** [comment]
In addition, I`m have one another problem ... Splashes (I do not know how to call it, lol :D) of embers on the server are not directed along the trajectory, which should be in fact. I`m don`t know how to fix it... https://prnt.sc/kikp8a

(I`m use spongeforge-1.12.2-2705-7.1.0-BETA-3291)

**Comment by DaedalusGame** [comment]
If you're using spongeforge, that's probably why. Open an issue on their tracker.
