### ISSUE TITLE
Inferno Forge Doesn't Work

### ISSUE THREAD

**Issue by hiddenspyman77** [DaedalusGame/EmbersRekindled#284]
I'm running RAD 1.41 on a Minecraft Server (Embers Rekindled 1.14 hotfix) and when I try to use the Inferno Forge, it starts to cook and then stop. None of the ember crystals are used up and the item with max heat remains at max heat but does not level up.

**Comment by DaedalusGame** [comment]
you're on a version where the inferno forge only requires and accepts very few ember crystals, about 2-3 crystals, this is fixed in newer versions.
