### ISSUE TITLE
Courtesy notification of fork

### ISSUE THREAD

**Issue by asanetargoss** [DaedalusGame/EmbersRekindled#292]
Hey, I just backported an old 1.11 version of the Embers code to 1.10, for maintenance/modpack-related reasons. This is a courtesy ticket to let you know of its existence. The source code is available here:

https://github.com/asanetargoss/EmbersHcA

To be honest, I haven't done much with it at this point, and haven't 100% decided what to do with it. The main reason you may be interested in this fork at this time is because it contains code which would in principle allow users of the 1.10 version of Embers to migrate to a 1.12 version of Embers. I don't have any plans to backport features from later iterations of Embers. That's about it!

**Comment by DaedalusGame** [comment]
ok
