### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Embers Rekindled (embers)

### ISSUE THREAD

**Issue by LostGameDev** [DaedalusGame/EmbersRekindled#295]
this is the crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FutureMC (future-mc-0.1.13.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  ratscore (rats-3.1.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/23/21 4:48 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Embers Rekindled (embers)
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/aspects/AspectRegistryEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:47)
	at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:52)
	at teamroots.embers.Embers.preInit(Embers.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thaumcraft.api.aspects.AspectRegistryEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path, and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 722310344 bytes (688 MB) / 1837629440 bytes (1752 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 139 mods loaded, 139 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                   | Source                                                | Signature                                |
	|:----- |:------------------------ |:------------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                | 1.12.2                    | minecraft.jar                                         | None                                     |
	| LCH   | mcp                      | 9.42                      | minecraft.jar                                         | None                                     |
	| LCH   | FML                      | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCH   | forge                    | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCH   | additionalresources      | 0.1.1                     | additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar | None                                     |
	| LCH   | futuremccore             | 0.1.12                    | minecraft.jar                                         | None                                     |
	| LCH   | dsurroundcore            | 3.5.5.0                   | minecraft.jar                                         | None                                     |
	| LCH   | crafttweaker             | 4.1.19                    | CraftTweaker2-1.12-4.1.19.jar                         | None                                     |
	| LCH   | mtlib                    | 3.0.6                     | MTLib-3.0.6.jar                                       | None                                     |
	| LCH   | modtweaker               | 4.0.17                    | modtweaker-4.0.17.jar                                 | None                                     |
	| LCH   | jei                      | 4.15.0.291                | jei_1.12.2-4.15.0.291.jar                             | None                                     |
	| LCH   | abyssalcraft             | 1.9.4.9                   | AbyssalCraft-1.12.2-1.9.4.9.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | acintegration            | 1.6.2                     | AbyssalCraft Integration-1.12.2-1.6.2.jar             | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | codechickenlib           | 3.1.8.341                 | CodeChickenLib-1.12.2-3.1.8.341-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare           | 1.12.2-2.5.221            | ancientwarfare-1.12.2-2.5.221.jar                     | None                                     |
	| LCH   | ancientwarfareautomation | 1.12.2-2.5.221            | ancientwarfare-1.12.2-2.5.221.jar                     | None                                     |
	| LCH   | ancientwarfarenpc        | 1.12.2-2.5.221            | ancientwarfare-1.12.2-2.5.221.jar                     | None                                     |
	| LCH   | ancientwarfarestructure  | 1.12.2-2.5.221            | ancientwarfare-1.12.2-2.5.221.jar                     | None                                     |
	| LCH   | ancientwarfarevehicle    | 1.12.2-2.5.221            | ancientwarfare-1.12.2-2.5.221.jar                     | None                                     |
	| LCH   | antiqueatlas             | 4.4.9                     | antiqueatlas-1.12.2-4.4.9.jar                         | None                                     |
	| LCH   | antiqueatlasoverlay      | 1.2                       | antiqueatlas-1.12.2-4.4.9.jar                         | None                                     |
	| LCH   | examplemod               | 1.0                       | antiqueatlas-1.12.2-4.4.9.jar                         | None                                     |
	| LCH   | appleskin                | 1.0.9                     | AppleSkin-mc1.12-1.0.9.jar                            | None                                     |
	| LCH   | armorchroma              | 1.3                       | armorchroma-1.3-1.12.2.jar                            | None                                     |
	| LCH   | baubles                  | 1.5.2                     | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCH   | astralsorcery            | 1.8.10                    | astralsorcery-1.12.2-1.8.10.jar                       | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | audiodeath               | 0.7.0_1.9-87aeca7         | audiodeath-1.9-0.7.0.50+87aeca7.jar                   | None                                     |
	| LCH   | backpacks16840           | 3.5.0                     | backpacks 1.12.2 - 3.5.0.jar                          | None                                     |
	| LCH   | base                     | 3.7.2                     | base-1.12.2-3.7.2.jar                                 | None                                     |
	| LCH   | mantle                   | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LCH   | bhc                      | 1.1.1                     | baubley-heart-canisters-1.12.2-1.1.1.jar              | 7b14aaee2dd17b12a140baecab28948fff3a263f |
	| LCH   | bettercompass            | 1.3.0                     | bettercompass-1.12.2-1.3.0.jar                        | None                                     |
	| LCH   | bibliocraft              | 2.4.4                     | BiblioCraft[v2.4.4][MC1.12.2].jar                     | None                                     |
	| LCH   | guideapi                 | 1.12-2.1.5-60             | Guide-API-1.12-2.1.5-60.jar                           | None                                     |
	| LCH   | bloodmagic               | 1.12.2-2.2.12-97          | BloodMagic-1.12.2-2.2.12-97.jar                       | None                                     |
	| LCH   | bloodmoon                | 1.5.3                     | Bloodmoon-MC1.12.2-1.5.3.jar                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bookshelf                | 2.3.589                   | Bookshelf-1.12.2-2.3.589.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | thaumcraft               | 6.1.BETA14                | Thaumcraft-1.12.2-6.1.BETA14.jar                      | None                                     |
	| LCH   | botania                  | r1.10-354                 | Botania r1.10-354.jar                                 | None                                     |
	| LCH   | cannibalism              | 5.6.3                     | Cannibalism-5.6.3-1.12.2.jar                          | None                                     |
	| LCH   | chameleon                | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| LCH   | clumps                   | 3.1.2                     | Clumps-3.1.2.jar                                      | None                                     |
	| LCH   | extendedrenderer         | v1.0                      | coroutil-1.12.1-1.2.32.jar                            | None                                     |
	| LCH   | coroutil                 | 1.12.1-1.2.32             | coroutil-1.12.1-1.2.32.jar                            | None                                     |
	| LCH   | configmod                | v1.0                      | coroutil-1.12.1-1.2.32.jar                            | None                                     |
	| LCH   | ctgui                    | 1.0.0                     | CraftTweaker2-1.12-4.1.19.jar                         | None                                     |
	| LCH   | crafttweakerjei          | 2.0.3                     | CraftTweaker2-1.12-4.1.19.jar                         | None                                     |
	| LCH   | creepingnether           | 2.0                       | Creeping Nether-2.0.jar                               | None                                     |
	| LCH   | custombackgrounds        | 1.0                       | CustomBackgrounds-MC1.12-1.1.1.jar                    | None                                     |
	| LCH   | custommainmenu           | 2.0.9                     | CustomMainMenu-MC1.12.2-2.0.9.jar                     | None                                     |
	| LCH   | cyclopscore              | 1.5.1                     | CyclopsCore-1.12.2-1.5.1.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | darktheme                | 12r                       | DarkTheme-1.12.2-12r.jar                              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | dmonsters                | 1.7                       | Deadly Monsters 1.71.jar                              | None                                     |
	| LCH   | death_compass            | 0.0.3                     | DeathCompass-0.0.3.jar                                | None                                     |
	| LCH   | defiledlands             | 1.4.2                     | defiledlands-1.12.2-1.4.2.jar                         | None                                     |
	| LCH   | orespawn                 | 3.3.0                     | OreSpawn-1.12-3.3.0.136.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | densemetals              | 1.2.0                     | DenseMetals-1.12-1.2.0.20.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | ding                     | 1.0.2                     | Ding-1.12.2-1.0.2.jar                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | dissolution              | 0.6.1                     | dissolution-1.12-0.6.1.jar                            | None                                     |
	| LCE   | embers                   | 1.18                      | EmbersRekindled-1.18.jar                              | None                                     |
	| LC    | evilcraft                | 0.10.78                   | EvilCraft-1.12.2-0.10.78.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LC    | evilcraftcompat          | 1.0.0                     | EvilCraft-1.12.2-0.10.78.jar                          | None                                     |
	| LC    | expandedbonemeal         | 1.2.1                     | expandedbonemeal-1.11-1.2.1.jar                       | None                                     |
	| LC    | extraalchemy             | 0.3.8.4-release           | extraalchemy-0.3.8.4-release.jar                      | None                                     |
	| LC    | eyesinthedarkness        | 0.1.0                     | EyesInTheDarkness-0.1.0.jar                           | None                                     |
	| LC    | familiarfauna            | 1.0.10                    | FamiliarFauna-1.12.2-1.0.10.jar                       | None                                     |
	| LC    | fastfurnace              | 1.3.1                     | FastFurnace-1.12.2-1.3.1.jar                          | None                                     |
	| LC    | fastleafdecay            | v14                       | FastLeafDecay-v14.jar                                 | None                                     |
	| LC    | forgelin                 | 1.8.4                     | Forgelin-1.8.4.jar                                    | None                                     |
	| LC    | friendlyfire             | 1.5.8                     | FriendlyFire-1.12.2-1.5.8.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | minecraftfuture          | 0.1.13                    | future-mc-0.1.13.jar                                  | None                                     |
	| LC    | ghostly                  | 1.0.4                     | ghostly-1.0.5.jar                                     | None                                     |
	| LC    | giacomos_map_merging     | 1.0                       | GiacomosMapMerging-1.12.2-1.1.jar                     | None                                     |
	| LC    | globalxp                 | v1.4                      | globalxp-1.12.x-v1.4.jar                              | None                                     |
	| LC    | gravestone               | 1.0.15                    | GraveStone-1.12.2-Graves-1.0.15.jar                   | None                                     |
	| LC    | gravestone-extended      | 1.2.6                     | GraveStone-1.12.2-Extended-1.2.6.jar                  | None                                     |
	| LC    | grue                     | 1.5.0                     | Grue-1.12.2-1.5.0.jar                                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LC    | halloween                | 0.9.2                     | Halloween-1.12-0.9.2.jar                              | None                                     |
	| LC    | uteamcore                | 2.2.4.133                 | u_team_core-1.12.2-2.2.4.133.jar                      | None                                     |
	| LC    | halloween_luckyblock     | 2.2.2.8                   | halloween_luckyblock-1.12.2-2.2.2.8.jar               | None                                     |
	| LC    | harvest                  | 1.12-1.2.7-20             | Harvest-1.12-1.2.7-20.jar                             | None                                     |
	| LC    | horror_movie_monsters    | 1.10.2                    | HMM1.10.2.jar                                         | None                                     |
	| LC    | hotornot                 | 1.1.2                     | HotOrNot-1.12-1.1.2-16.jar                            | None                                     |
	| LC    | llibrary                 | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire               | 1.4.0                     | iceandfire-1.4.0-1.12.2.jar                           | None                                     |
	| LC    | ichunutil                | 7.2.2                     | iChunUtil-1.12.2-7.2.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | inspirations             | 1.12.2-0.2.8              | Inspirations-1.12.2-0.2.8.jar                         | None                                     |
	| LC    | inventorytweaks          | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                | 1.12.2-7.0.40.824         | ironchest-1.12.2-7.0.40.824.jar                       | None                                     |
	| LC    | jeresources              | 0.9.2.60                  | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
	| LC    | libraryex                | 1.0.12                    | LibraryEx-1.12.2-1.0.12.jar                           | None                                     |
	| LC    | placebo                  | 1.6.0                     | Placebo-1.12.2-1.6.0.jar                              | None                                     |
	| LC    | magicalmap               | 3.1.0                     | Magical Map-1.12.2-3.1.0.jar                          | None                                     |
	| LC    | mobamputation            | 7.0.0                     | MobAmputation-1.12.2-7.0.0.jar                        | None                                     |
	| LC    | mobdismemberment         | 7.0.0                     | MobDismemberment-1.12.2-7.0.0.jar                     | None                                     |
	| LC    | mobends                  | 0.24                      | mobends-0.24_for_MC-1.12.jar                          | None                                     |
	| LC    | modnametooltip           | 1.10.1                    | modnametooltip_1.12.2-1.10.1.jar                      | None                                     |
	| LC    | moreoverlays             | 1.13                      | moreoverlays-1.13-mc1.12.1.jar                        | None                                     |
	| LC    | mousetweaks              | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                         | None                                     |
	| LC    | multimob                 | 1.0.5                     | multimob-1.0.5.jar                                    | None                                     |
	| LC    | mutantmobs               | 1.0.1                     | Mutant Mobs V1.0.1.jar                                | None                                     |
	| LC    | netherex                 | 2.0.15                    | NetherEx-1.12.2-2.0.15.jar                            | None                                     |
	| LC    | netherportalfix          | 5.3.17                    | NetherPortalFix_1.12.1-5.3.17.jar                     | None                                     |
	| LC    | nightmares               | 1.0.11                    | Nightmares-1.12.2-1.0.11.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | spookytree               | 1.12.2a                   | Pam's Spooky Tree 1.12.2a.jar                         | None                                     |
	| LC    | proxyslib                | 1.1.0                     | Proxy's Lib-1.12.2-1.1.0.jar                          | 798adbf4d7cb5e70efba22362a51cb84cd4e1dd7 |
	| LC    | rats                     | 3.1.0                     | rats-3.1.0.jar                                        | None                                     |
	| LC    | realistictorches         | 2.1.1                     | RealisticTorches-1.12.2-2.1.1.jar                     | None                                     |
	| LC    | resourceloader           | 1.5.3                     | ResourceLoader-MC1.12.1-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | roguelike                | 1.8.0                     | RoguelikeDungeons-1.12.2-1.8.0.jar                    | None                                     |
	| LC    | simplylight              | 1.12.2-0.8.7              | simplylight-1.12.2-0.8.7.jar                          | None                                     |
	| LC    | soot                     | 1.6                       | Soot-1.6.jar                                          | None                                     |
	| LC    | spartanshields           | 1.4.1                     | SpartanShields-1.12.2-1.4.1.jar                       | None                                     |
	| LC    | spartanweaponry          | beta 1.1.2                | SpartanWeaponry-1.12.2-beta-1.1.2.jar                 | None                                     |
	| LC    | srparasites              | 1.9.0                     | SRParasites-1.12.2v1.9.0ALPHA14.jar                   | None                                     |
	| LC    | storagedrawers           | 1.12-5.3.5                | StorageDrawers-1.12.2-5.3.6.jar                       | None                                     |
	| LC    | stygian                  | 1.0.4                     | stygian-1.0.4.jar                                     | None                                     |
	| LC    | surge                    | 2.0.77                    | Surge-1.12.2-2.0.77.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | thaumicjei               | 1.2.1                     | ThaumicJEI-1.12.2-1.2.4-9.jar                         | None                                     |
	| LC    | thaumicperiphery         | 0.2.3                     | thaumicperiphery-0.2.3.jar                            | None                                     |
	| LC    | thebetweenlands          | 3.3.8                     | TheBetweenlands-3.3.8-universal.jar                   | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LC    | tombstone                | 3.6.2                     | tombstone-3.6.2-1.12.2.jar                            | None                                     |
	| LC    | torohealthmod            | 1.12.2-11                 | torohealth-1.12.2-11.jar                              | None                                     |
	| LC    | trumpetskeleton          | 1.12-1.0.2.1              | trumpetskeleton-1.12-1.0.2.1.jar                      | None                                     |
	| LC    | twilightforest           | 3.7.424                   | twilightforest-1.12.2-3.7.424-universal.jar           | None                                     |
	| LC    | vampirism                | 1.4.2                     | Vampirism-1.12.2-1.4.2.jar                            | None                                     |
	| LC    | teamlapen-lib            | 1.4.2                     | Vampirism-1.12.2-1.4.2.jar                            | None                                     |
	| LC    | vampirism_integrations   | vampirism_integrations    | VampirismIntegrations-1.12.2-1.0.0.jar                | None                                     |
	| LC    | waystones                | 4.0.43                    | Waystones_1.12.2-4.0.43.jar                           | None                                     |
	| LC    | weirdinggadget           | 1.0                       | weirdinggadget-1.12.2-2.0.5-universal.jar             | None                                     |
	| LC    | witherskelefix           | 2.6.3                     | WitherSkeletonTweaks-1.12.2-2.6.3.jar                 | None                                     |
	| LC    | wolfarmor                | 1.12.2-2.1.0-RELEASE      | wolfarmor-1.12.2-2.1.0.26-RELEASE.jar                 | None                                     |
	| LC    | worldprimer              | 0.6.0-dev.20190814.220944 | worldprimer-1.12.2-0.6.0-dev.20190814.220944.jar      | 2b03e1423915a189b8094816baa18f239d576dff |
	| LC    | zombieawareness          | 1.12.1-1.11.16            | zombieawareness-1.12.1-1.11.16.jar                    | None                                     |
	| LC    | orelib                   | 3.5.2.3                   | OreLib-1.12.2-3.5.2.3.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround                | 3.5.5.0                   | DynamicSurroundings-1.12.2-3.5.5.0.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | pumpkinlauncher          | 1.12.2-1.7.0              | Jack-O'-Launcher-1.12.2-1.7.0.jar                     | None                                     |
	| LC    | midnight                 | 0.3.5                     | themidnight-0.3.5.jar                                 | None                                     |
	| LC    | weeping-angels           | 1.12.2-39                 | weeping-angels-39.jar                                 | None                                     |

	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
BCModPlugin (backpacks 1.12.2 - 3.5.0.jar)
  brad16840.core.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.5.0.jar)
  org.orecruncher.dsurround.asm.Transformer
ratscore (rats-3.1.0.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.77' Renderer: 'NVIDIA GeForce RTX 2070/PCIe/SSE2'
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- RatsPlugin (Enabled/Not Forced)
		- TwilightForestPlugin (Enabled/Not Forced)

**Comment by DaedalusGame** [comment]
update thaumcraft
