### ISSUE TITLE
massive lag due to the sheer amount of dawnstone anvil recipes

### ISSUE THREAD

**Issue by Darkmega18** [DaedalusGame/EmbersRekindled#31]
as it appears, literally everything in the game can get that core thing put on it, as well as upgrades or something, not to mention the "renamed item" recipes that show up. This is causing extreme lag when switching to it's crafting menu when searching recipes or for uses for items and it happens to start on the dawnstone anvil section cause of no other uses.

Is this a bug that literally everything can be given a heat gauge and stuff? I don't recall having nearly as much issue with crafting recipe searches using embers from the old version before soot updated to require this version.

**Comment by MorzanTLD** [comment]
Even if the ability to add heat to literally all items isn't a bug, I would still like to not have them listed in JEI whenever I look at an item even if it doesn't personally cause me significant amounts of lag.

**Comment by Darkmega18** [comment]
probably a smaller pack then. but in a large pack like mine, the game literally freezes for several seconds even for a friend with a vastly better computer.

**Comment by DaedalusGame** [comment]
does this still happen in the newest released version?

**Comment by Darkmega18** [comment]
nope. fixed. Thanks a bunch. didn't notice the update until I was told from the discord.
