### ISSUE TITLE
Crash while ticking entity

### ISSUE THREAD

**Issue by Diamssword** [DaedalusGame/EmbersRekindled#33]
Exeprienced client crash when seeing entities while playing on server
https://pastebin.com/dA7zjhhu

**Comment by TornadoOfSoup** [comment]
People on my server had the same crash, the ember projectile location was right in front of an underground embers structure. We can't figure out how to reproduce the crash or what caused it, but killing the entity allowed people to get back on the server. (the server didn't crash, just the people on it)

**Comment by Diamssword** [comment]
Yup , same here but was happening with a lot of entities, found out or was another mod, Valkirian Warfare wich was messing up the DataWatcher

**Comment by DaedalusGame** [comment]
figures
