### ISSUE TITLE
Crash during game load

### ISSUE THREAD

**Issue by Dragnier** [DaedalusGame/EmbersRekindled#38]
https://github.com/V0idWa1k3r/Aetherworks/issues/5#issuecomment-414923396

The comment linked above is where I posted a crash report when I thought this might be due to Aetherworks. However, I tried to load without it and got the following:

https://paste.dimdev.org/erunelexel.mccrash

Though, I also added Soot at the same time I removed Aetherworks.

**Comment by DaedalusGame** [comment]
Dupe of #35
