### ISSUE TITLE
JEI Recipe integration appears broken

### ISSUE THREAD

**Issue by Mario90900** [DaedalusGame/EmbersRekindled#42]
After installing Embers Rekindled and Soot alongside JEI, it appears that Embers loses all JEI integration and its impossible to tell what any of the recipes are. I tested this in a separate test instance with very few mods installed, and if I swap back to Embers all of the JEI integration returns. I realize this might be kinda lackluster for an issue report, but I hope that the problem can be found.

**Comment by DaedalusGame** [comment]
can you get me a full game log of when the problem happens? JEI problems are impossible to debug without logs because all errors are silently written to the log and break *everything* down the line.

**Comment by terrapin47** [comment]
What version of each?

I can install the latest version of Embers Rekindled, Soot, and JEI and don't have this issue.

![image](https://user-images.githubusercontent.com/13740412/44495224-27751300-a63d-11e8-972c-bbba6122e990.png)

**Comment by Mario90900** [comment]
Aha, that was it. I didn't realize that Soot had updated about a week ago, and updating Soot fixed it all. Sorry about that!
