### ISSUE TITLE
[1.12.2] [1.7] "Fixes" the Mojang lang file parser breaks Blood Magic chat messages

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/EmbersRekindled#46]
Hi,

the "fix" for Mojangs lang file parser breaks some messages from Blood Magic, for instance the current Essence display in chat:

https://github.com/WayofTime/BloodMagic/blob/d54c828fba3c673a4401c470a93040f03e0eb2c1/src/main/resources/assets/bloodmagic/lang/en_US.lang#L398

It only shows tooltip.bloodmagic.sigil.divination.currentEssence instead of the defined string, it's fixed when reverting EmbersRekindled to 1.6.

Thanks for looking into it.

Best regards,
wamc

**Comment by DaedalusGame** [comment]
![hahayes](https://user-images.githubusercontent.com/9559216/45093494-d5da8700-b118-11e8-8c5b-52e32241e4fd.png)

**Comment by DaedalusGame** [comment]
I'm being told that bloodmagic is using %d in a TextComponentTranslation, which will throw a format exception.
