### ISSUE TITLE
Broken formatting placeholder pattern

### ISSUE THREAD

**Issue by marvin-roesch** [DaedalusGame/EmbersRekindled#48]
You replace the language parser's pattern for "fixing up" invalid formatting placeholder here:
https://github.com/DaedalusGame/EmbersRekindled/blob/842c22201f8bfe10f5188038207a40bc4bf98750/src/main/java/teamroots/embers/proxy/ClientProxy.java#L33
This is fundamentally broken and suggests to me that you do not know Java's regex engine. It seems like your intention was to to have it replace occurrences of `%$1s` with itself, making the replacement effectively a no-op.

However, this leads to problems if a language file contains a line such as the following:
```properties
some.key=Muh awesome lang %%$1s
```
As you can tell, this example contains a string that's matched by your replaced pattern. Upon loading the game, this will lead to the following exception being thrown:
```
java.lang.IndexOutOfBoundsException: No group 1
```
The reason for this is that `$n` for any non-negative integer `n` is special notation in the replacement for a regex search & replace operation in Java. It tells the engine to put whatever was the `n`th matching group in the into the resulting string (`0` being the entire matched string).

As a consequence, your change with the intention of making the replacement a no-op in fact breaks a perfectly valid language file.

I'd suggest removing this pattern overriding altogether, it can both lead to breakage and messes with modder expectations, because anyone who looks into the details of MC locale loading will come across the Vanilla pattern and will expect it to work.

**Comment by DaedalusGame** [comment]
I actually looked this up today, suspecting this to be the case and didn't find anything about this in the oracle javadocs. Thank you for actually giving me a reason (that isn't "I post %d to chat and it worked fine before") not to do this.

**Comment by TehNut** [comment]
>that isn't "I post %d to chat and it worked fine before"

That's literally the only reason you need. You made a ***breaking*** change to how vanilla functions and what mods expect. You have absolutely no right to police other mods to work around changes like that.

**Comment by DaedalusGame** [comment]
rofl
