### ISSUE TITLE
Dawnstone anvil issue with Jei

### ISSUE THREAD

**Issue by Lloergwaed** [DaedalusGame/EmbersRekindled#52]
when comming upon the jei entries for Dawnstone anvil there is a huge lag spike of between 5 to 15 sec.
any idea why?

**Comment by DaedalusGame** [comment]
what version are you using?

**Comment by Lloergwaed** [comment]
ember rekindle 1.8 for mc 1.12

**Comment by tyler489** [comment]
https://github.com/DaedalusGame/EmbersRekindled/issues/31
?

**Comment by DaedalusGame** [comment]
it was supposed to be fixed already, not sure why it flared back up

**Comment by Lloergwaed** [comment]
just realize "all item" in jei have a dawnstone section in jei even when their is no recipe and it's those recipe that cause the lag

**Comment by dredhorse** [comment]
can confirm this issue with 1.8. One way to fix this would probably be to not register all the "repair" etc recipies with jei but put up an "info" page into jei for usage of the dawnstawn anvil explaining what it can do.

Looks like soot handles it stamping recipe differently.

**Comment by DaedalusGame** [comment]
you're telling me the soot rename recipe doesn't cause the same lag?

**Comment by dredhorse** [comment]
looks like it, the inscription stamp only shows one recipe, but it looks like all items cycling through it. I guess soot pulls all stuff ones and that is is. To be honest, IMO both should be done with an info page in jei for usage, the soot renaming and the anvil repairing
