### ISSUE TITLE
[1.12.2] [1.8] Alchemy issues

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/EmbersRekindled#53]
Hi,

- currently the alchemy tablet seems to always give back the output if the amount of ash is in the range of the recipe. For instance I tried to craft Ashen fabric with 12, 16 and 24 ash in the iron and lead aspectus sockets, but never got some alchemical waste. (Instead the fabric itself)
- Also there seems to be an issue if every aspectus has the same amount of ash defined. Aetherworks does this for the Aetherium Crown:
https://github.com/V0idWa1k3r/Aetherworks/blob/09ed6f20f2a752a98bf6b63056491f04926b487f/src/main/java/v0id/aw/common/recipe/AWRecipes.java#L46
That's the only recipe which does give me back some alchemical waste, but with a Inaccuracy of 0 in all aspects:
![inac](https://user-images.githubusercontent.com/33242447/45503823-525c0e00-b788-11e8-85e9-fb1daa1392ce.png)
I changed one of those 16 to 0 and recompiled it and the recipe works like a charm. (with the other bug mentioned above)

- In the past (before Rekindled was a thing) I used a simple crafttweaker script to test alchemy:
`mods.embers.Alchemy.add(<minecraft:diamond>,[<minecraft:stone>,null,null,null,null],12 to 16,12 to 16,12 to 16,12 to 16,12 to 16);`
This doesn't work anymore, here's the crafttweaker.log: https://gist.github.com/wamc2017/1d777312029db00ead2f2fa3bd43d86c
Did anything change between the migration of the ct support from Soot to Embers or is this a bug (or is anything wrong with this script?)

Thanks for looking into it.

Best regards,
wamc

**Comment by DaedalusGame** [comment]
about the CT integration: you have to specify a map ala `{ "iron" : 12 to 16, "silver" : 12 to 16 }` (etc) now
i will investigate the other two issues

**Comment by wamc2017** [comment]
Thanks, works like a charm.

Btw. using `mods.embers.Alchemy.add(<minecraft:diamond>,[<minecraft:stone>,null,null,null,null],{"iron" : 16 to 16, "silver" : 16 to 16, "dawnstone" : 16 to 16, "lead" : 16 to 16, "copper" : 16 to 16});` also produces Alchemical waste with Inaccurancy 0 for all aspects.
