### ISSUE TITLE
Add Geologic Seperator

### ISSUE THREAD

**Issue by DaedalusGame** [DaedalusGame/EmbersRekindled#69]
- Like a casting basin
- Goes on a Melter (only 1)
- When the Melter melts an ore, it will produce a bit of extra molten metal related to the ore.

Extra outputs: 
- Lead Ore -> Silver (Galena)
- Silver Ore -> Lead (Galena)
- Gold Ore -> Silver (Electrum)
- Copper Ore -> Gold
- Aluminium Ore -> Iron
- Iron Ore -> Nickel (Meteoric Iron)
- Tin Ore -> Lead (Teallite)

**Comment by drhaber** [comment]
Can this component get CraftTweaker support?
