### ISSUE TITLE
Duplicating Mixer and Melter Centrifuge maybe more

### ISSUE THREAD

**Issue by TickingTimebomb1** [DaedalusGame/EmbersRekindled#90]
The Melter and Mixer Centrifuge both when placed create a block above them, when you break one, they drop 2 of the item and break both

**Comment by DaedalusGame** [comment]
we've never had this issue on our test server, but if you're playing revelations, it might a weird dupe bug that affects several other blocks.

**Comment by TickingTimebomb1** [comment]
Did more looking into it, its on another modpack, its an issue with the Tetra mod not Embers. Just Embers was the first case I saw it
